name: secret-scan

on:
  workflow_call:

jobs:
  secret-scan:
    name: secret-scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/code \
            zricethezav/gitleaks:latest \
            detect --source="/code" --verbose --report-format=sarif --report-path="/code/gitleaks.sarif"