name: semgrep

on:
  workflow_call:

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"
          generateSarif: "1"